# -*- python -*-

import waflib.Logs as msg

PACKAGE = {
    'name': 'Control/AthenaCommon',
    'author': ['atlas collaboration'],
}

def pkg_deps(ctx):
    ctx.use_pkg('AtlasPolicy')

    #FIXME
    ctx.use_pkg('External/AtlasPython')
    #ctx.use_pkg('External/AtlasTCMalloc')
    return

def configure(ctx):
    msg.debug ('[configure] package name: '+PACKAGE['name'])
    return

def build(ctx):



    ctx.install_headers()

    ctx.build_pymodule(source=['python/*.py', 'python/Utils'])

    ctx.install_joboptions(
        source=[
            'share/AthenaCommonFlags.py',
            'share/Atlas.UnixStandardJob.py',
            'share/Atlas_Gen.UnixStandardJob.py',
            'share/Bootstrap.py',
            'share/Execution.py',
            'share/JobOptTraceInclude.py',
            'share/MemTraceInclude.py',
            'share/Preparation.py',
            'share/runbatch.py',
            ]
        )

    ctx.install_scripts(
        source=[
            'share/athena.py',
            'share/athena.C',
            'share/athena-app.py',
            'share/chappy.py',
            'share/find_cfg_dups.py',
            'test/*.py',
            'share/test_cfg_pickling.py',
            ]
        )

    ctx.hwaf_declare_runtime_alias('athena', 'athena.py')
    ctx.hwaf_declare_runtime_alias('athena-app', 'athena-app.py')
    
    return
### EOF ###
